<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.saucedemo</groupId>
    <artifactId>SauceDemoFramework</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>SauceDemoFramework</name>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- Selenium WebDriver -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.34.0</version>
        </dependency>

        <!-- TestNG -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.10.2</version>
            <scope>test</scope>
        </dependency>

        <!-- WebDriverManager -->
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>6.1.0</version>
        </dependency>

    </dependencies>
    
    <build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>3.2.5</version>
            
               <configuration>
                <suiteXmlFiles>

                    <!-- Default suite execution from Eclipse / Maven -->
                    <!-- <suiteXmlFile>Smoke-Suite.xml</suiteXmlFile>
                    <suiteXmlFile>RegressionSuite.xml</suiteXmlFile>-->

                    <!-- For command line execution use this instead -->
                     <suiteXmlFile>${suiteXmlFile}</suiteXmlFile> 
                   <!--  <suiteXmlFile>$RegressionSuite.xml</suiteXmlFile> --> 

                </suiteXmlFiles>
                <reportsDirectory>target/surefire-reports</reportsDirectory>
            </configuration>

        </plugin>
    </plugins>
</build>

</project>